import { heroEquipment } from "../HeroEquipment";

export const arabia = {
  heroes: {
    Emir: {
      id: 0,
      startingEquipment: ["Sztylet", "Chopesz"],
      cost: 65,
      number: 1,
      equipmentList: heroEquipment["Kupiecka karawana z Arabii"].Bohaterowie,
      type: "Bohater",
      stats: {
        Początkowa: [4, 4, 4, 3, 3, 2, 4, 1, 8],
        Maksymalna: [5, 6, 6, 4, 4, 3, 6, 4, 9],
      },
      rules: ["Dowódca", "Przepastne trzewia", "Żyłka handlowa"],
      exp: 20,
      skills: [0, 1, 2, 3, 4, 5],
    },
    Wezyr: {
      id: 1,
      startingEquipment: ["Sztylet", "Kostur"],
      cost: 45,
      number: 1,
      equipmentList: {
        ...heroEquipment["Kupiecka karawana z Arabii"].Bohaterowie,
        ...{
          "Tradycja Metalu": [0, 4, "Tradycja"],
          "Magia Żywiołów": [0, 4, "Tradycja"],
        },
      },
      type: "Bohater",
      stats: {
        Początkowa: [4, 3, 3, 3, 3, 1, 3, 1, 8],
        Maksymalna: [5, 6, 6, 4, 4, 3, 6, 4, 9],
      },
      rules: ["Mag", "Przepastne trzewia", "Żyłka handlowa"],
      exp: 12,
      skills: [],
    },
    "Handlarz niewolników": {
      id: 2,
      startingEquipment: ["Sztylet", "Łapacz"],
      cost: 35,
      number: 2,
      equipmentList: heroEquipment["Kupiecka karawana z Arabii"].Bohaterowie,
      type: "Bohater",
      stats: {
        Początkowa: [4, 3, 3, 3, 3, 2, 4, 1, 7],
        Maksymalna: [5, 6, 6, 4, 4, 3, 6, 4, 9],
      },
      rules: ["Handlarz niewolników", "Żyłka handlowa"],
      exp: 8,
      skills: [0, 3, 5],
    },
    Wieszcz: {
      id: 3,
      startingEquipment: ["Sztylet"],
      cost: 15,
      number: 1,
      equipmentList: heroEquipment["Kupiecka karawana z Arabii"].Bohaterowie,
      type: "Bohater",
      stats: {
        Początkowa: [4, 2, 2, 3, 3, 2, 4, 1, 6],
        Maksymalna: [5, 6, 6, 4, 4, 3, 6, 4, 9],
      },
      rules: ["Szczęście", "Tarot", "Wzgardzony", "Żyłka handlowa"],
      exp: 0,
      skills: [0, 2, 4, 5],
    },
    Niewolnik: {
      id: 4,
      startingEquipment: ["Broń improwizowana"],
      cost: 10,
      number: 15,
      equipmentList: {},
      type: "Stronnik",
      stats: {
        Początkowa: [4, 2, 2, 3, 3, 1, 3, 1, 2],
        Maksymalna: [5, 6, 6, 4, 4, 3, 6, 4, 9],
      },
      rules: ["Mięso armatnie", "Niewolnik", "Rozmiar rzondzi"],
    },
    Żołnierz: {
      id: 6,
      startingEquipment: ["Sztylet"],
      cost: 20,
      number: 15,
      equipmentList: heroEquipment["Kupiecka karawana z Arabii"].Stronnicy,
      type: "Stronnik",
      stats: {
        Początkowa: [4, 3, 3, 3, 3, 1, 3, 1, 7],
        Maksymalna: [5, 6, 6, 4, 4, 3, 6, 4, 9],
      },
      rules: ["Chorążowie & sygnaliści", "Drużyna obsługi"],
    },
    Dżinn: {
      id: 6,
      startingEquipment: ["Broń naturalna (przebicie pancerza)"],
      cost: 45,
      number: 3,
      equipmentList: {},
      type: "Stronnik",
      stats: {
        Początkowa: [4, 4, 0, 4, 3, 1, 4, 2, 6],
        Maksymalna: [4, 4, 0, 4, 3, 1, 4, 2, 6],
      },
      rules: [
        "Demon",
        "Genius",
        "Istota magiczna (Tradycja Niebios)",
        "Lot",
        "Strach",
      ],
    },
    Nomada: {
      id: 7,
      startingEquipment: [
        "Sztylet",
        "Chopesz",
        "Łuk krótki",
        "Koń bojowy",
        "Siodło & uprząż",
      ],
      cost: 80,
      number: 3,
      equipmentList: heroEquipment["Kupiecka karawana z Arabii"].Nomada,
      type: "Stronnik",
      stats: {
        Początkowa: [4, 3, 4, 3, 3, 1, 3, 1, 7],
        Maksymalna: [5, 6, 6, 4, 4, 3, 6, 4, 9],
        "Koń bojowy": [8, 3, 0, 3, "-", "-", 3, 1, 5],
      },
      rules: ["Kawalerzysta", "Lekka jazda", "Ranger", "Zwiadowca"],
    },
    Derwisz: {
      id: 8,
      startingEquipment: ["Chopesz"],
      cost: 45,
      number: 5,
      equipmentList: heroEquipment["Kupiecka karawana z Arabii"].Derwisz,
      type: "Stronnik",
      stats: {
        Początkowa: [4, 3, 3, 4, 4, 1, 3, 1, 10],
        Maksymalna: [5, 6, 6, 4, 4, 3, 6, 4, 9],
      },
      rules: ["Fanatyk, Furia"],
    },
    Ifryt: {
      id: 9,
      startingEquipment: ["Broń naturalna (płonący atak)"],
      cost: 150,
      number: 1,
      equipmentList: {},
      type: "Stronnik",
      stats: {
        Początkowa: [6, 4, 0, 5, 4, 3, 4, 3, 6],
        Maksymalna: [6, 4, 0, 5, 4, 3, 4, 3, 6],
      },
      rules: [
        "Bycza szarża",
        "Demon",
        "Duży cel",
        "Genius",
        "Głód krwi",
        "Nienawiść",
        "Odwieczny konflikt",
        "Ogrnista korona",
        "Przepastne trzewia",
        "Strach",
        "Wielkolud",
      ],
    },
    Więźniarka: {
      id: 10,
      startingEquipment: [],
      cost: 185,
      number: 1,
      equipmentList: {},
      type: "Machina",
      stats: {
        Powóz: ["-", "-", "-", 4, 8, 8, "-", "-", "-"],
        Koń: [8, 3, 0, 3, "-", "-", 3, 1, 5],
        "Koń ": [8, 3, 0, 3, "-", "-", 3, 1, 5],
      },
      rules: ["Duży cel", "Machina wojenna", "Powóz", "Więźniarka"],
    },
    "Latający dywan": {
      id: 11,
      startingEquipment: [],
      cost: 150,
      number: 1,
      equipmentList: {},
      type: "Machina",
      stats: {
        Początkowa: [6, 3, 0, 4, 5, 3, 6, 2, 6],
        Maksymalna: [6, 3, 0, 4, 5, 3, 6, 2, 6],
      },
      rules: [
        "Demon",
        "Duży cel",
        "Lot",
        "Nalot dywanowy",
        "Potwór",
        "Przepastne trzewia",
        "Strach",
        "Trafienie z uderzenia",
        "Tratowanie",
        "Wielkolud",
        "Wierzchowiec",
        "Latający dywan",
      ],
    },
  },
  limit: 600,
  minModels: 3,
  maxModels: 15,
  name: "Kupiecka karawana z Arabii",
  nature: "Neutralna",
  armyRules: ["Kontakty handlowe (2)", "Podatek", "Rozrzutni", "Zamożność"],
  mercenaries: [
    "Balistyk",
    "Bombardier",
    "Czarownica",
    "Gladiator",
    "Goniec",
    "Kartograf",
    "Kupiec",
    "Łowca nagród",
    "Magus",
    "Medyk",
    "Minstrel",
    "Miotacz ołowiu",
    "Ochroniarz",
    "Ordynans",
    "Pogromca Trolli",
    "Poszukiwacz złota",
    "Rozbójnik",
    "Rycerz najemny",
    "Skryba",
    "Strażnik dróg",
    "Szpieg",
    "Tileański kusznik",
    "Woźnica",
    "Zwadźca",
    "Zwiadowca",
  ],
};
