import { heroEquipment } from "../HeroEquipment";

export const eshin = {
  heroes: {
    Nocarz: {
      id: 0,
      startingEquipment: ["Sztylet", "Dmuchawka"],
      cost: 70,
      number: 1,
      equipmentList: heroEquipment["Zwiadowcze stado klanu Eshin"].Bohaterowie,
      type: "Bohater",
      stats: {
        Początkowa: [6, 4, 4, 3, 3, 2, 5, 1, 7],
        Maksymalna: [6, 6, 6, 4, 4, 3, 7, 4, 7],
      },
      rules: ["Dowódca", "Mistrz skrytobójstwa", "Ranger", "Zasadzka"],
      exp: 20,
      skills: [0, 1, 4, 5],
    },
    Zaklinacz: {
      id: 1,
      startingEquipment: ["Sztylet", "Kostur"],
      cost: 50,
      number: 1,
      equipmentList: heroEquipment["Zwiadowcze stado klanu Eshin"].Bohaterowie,
      type: "Bohater",
      stats: {
        Początkowa: [6, 3, 3, 3, 3, 1, 4, 1, 6],
        Maksymalna: [6, 6, 6, 4, 4, 3, 7, 4, 7],
      },
      rules: ["Mag (Tradycja Skrytości", "Ranger", "Zasadzka"],
      exp: 8,
      skills: [0, 2, 4, 5],
    },
    Czarnoszczur: {
      id: 2,
      startingEquipment: ["Sztylet", "Halabarda"],
      cost: 45,
      number: 1,
      equipmentList: heroEquipment["Zwiadowcze stado klanu Eshin"].Bohaterowie,
      type: "Bohater",
      stats: {
        Początkowa: [6, 4, 3, 3, 3, 1, 5, 1, 5],
        Maksymalna: [6, 6, 6, 4, 4, 3, 7, 4, 7],
      },
      rules: ["Podoficer", "Ranger", "Zimnokrwisty"],
      exp: 8,
      skills: [0, 1, 3, 4, 5],
    },
    "Łowca niewolników": {
      id: 3,
      startingEquipment: ["Sztylet", "Łapacz"],
      cost: 45,
      number: 1,
      equipmentList: heroEquipment["Zwiadowcze stado klanu Eshin"].Bohaterowie,
      type: "Bohater",
      stats: {
        Początkowa: [6, 3, 3, 3, 3, 1, 5, 1, 5],
        Maksymalna: [6, 6, 6, 4, 4, 3, 7, 4, 7],
      },
      rules: ["Handlarz niewolników", "Ranger"],
      exp: 8,
      skills: [0, 1, 4, 5],
    },
    Niewolnik: {
      id: 4,
      startingEquipment: ["Broń improwizowana"],
      cost: 10,
      number: 15,
      equipmentList: {},
      type: "Stronnik",
      stats: {
        Początkowa: [4, 2, 2, 3, 3, 1, 3, 1, 2],
        Maksymalna: [5, 6, 6, 4, 4, 3, 6, 4, 9],
      },
      rules: ["Mięso armatnie", "Niewolnik", "Rozmiar rzondzi"],
    },
    "Posłaniec nocy": {
      id: 5,
      startingEquipment: ["Sztylet", "Broń miotana (gwiazdki)"],
      cost: 30,
      number: 15,
      equipmentList: heroEquipment["Zwiadowcze stado klanu Eshin"].Stronnicy,
      type: "Stronnik",
      stats: {
        Początkowa: [6, 3, 3, 3, 3, 1, 5, 1, 6],
        Maksymalna: [6, 6, 6, 4, 4, 3, 7, 4, 7],
      },
      rules: [
        "Chorążowie & sygnaliści",
        "Drużyna obsługi",
        "Ranger",
        "Zasadzka",
        "Cichy marsz",
      ],
    },
    "Rynsztokowiec": {
      id: 6,
      startingEquipment: ["Sztylet", "Khutar"],
      cost: 40,
      number: 7,
      equipmentList: heroEquipment["Zwiadowcze stado klanu Eshin"].Stronnicy,
      type: "Stronnik",
      stats: {
        Początkowa: [6, 4, 3, 3, 3, 1, 5, 1, 6],
        Maksymalna: [6, 6, 6, 4, 4, 3, 7, 4, 7],
      },
      rules: ["Ranger", "Saper", "Zasadzka", "Zwiadowca"],
    },
    "Wielki szczur": {
      id: 7,
      startingEquipment: ["Broń naturalna"],
      cost: 20,
      number: 15,
      equipmentList: {},
      type: "Stronnik",
      stats: {
        Początkowa: [6, 2, 0, 3, 3, 1, 4, 1, 3],
        Maksymalna: [6, 2, 0, 3, 3, 1, 4, 1, 3],
      },
      rules: ["Murołaz", "Sfora", "Zwierzę"],
    },
    Rydwan: {
      id: 8,
      startingEquipment: [],
      cost: 125,
      number: 1,
      equipmentList: {},
      type: "Machina",
      stats: {
        Rydwan: ["-", "-", "-", 5, 5, 8, "-", "-", "-"],
        Wilkoszczur: [9, 3, 0, 3, "-", "-", 4, 1, 3],
        "Wilkoszczur ": [9, 3, 0, 3, "-", "-", 4, 1, 3],
      },
      rules: ["Duży cel", "Machina wojenna", "Rydwan"],
    },
    Więźniarka: {
      id: 9,
      startingEquipment: [],
      cost: 175,
      number: 1,
      equipmentList: {},
      type: "Machina",
      stats: {
        Powóz: ["-", "-", "-", 4, 8, 8, "-", "-", "-"],
        Wilkoszczur: [9, 3, 0, 3, "-", "-", 4, 1, 3],
        "Wilkoszczur ": [9, 3, 0, 3, "-", "-", 4, 1, 3],
      },
      rules: ["Duży cel", "Machina wojenna", "Powóz", "Więźniarka"],
    },
  },
  limit: 500,
  minModels: 3,
  maxModels: 15,
  name: "Zwiadowcze stado klanu Eshin",
  nature: "Chaotyczna",
  armyRules: ["Rozrzutni", "W nogi!"],
  mercenaries: ["Szczurogr", "Szpieg", "Złodziej"],
};
