import { heroEquipment } from "../HeroEquipment";

export const khazadzi = {
    heroes: {
      Tan: {
        id: 0,
        startingEquipment: ["Sztylet", "Topór krasnoludów"],
        cost: 75,
        number: 1,
        equipmentList:
          heroEquipment["Khazadzi z Gór Krańca Świata"].Bohaterowie,
        type: "Bohater",
        stats: {
          Początkowa: [3, 5, 4, 4, 4, 2, 3, 1, 9],
          Maksymalna: [4, 7, 6, 4, 5, 3, 5, 4, 10],
        },
        rules: [
          "Dowodzenie",
          "Dowódca",
          "Krzepki",
          "Nieustępliwość",
          "Odporność na magię (2)",
          "Pomiot podmroku",
          "Rankor",
          "Rewelator",
          "Trudny do zabicia",
          "Uporczywość",
          "Wojownik podziemny",
          "Zabobonny lęk",
        ],
        exp: 20,
        skills: [0, 1, 2, 3, 5],
      },
      "Kowal Run": {
        id: 1,
        startingEquipment: ["Sztylet", "Buława/Maczuga/Młot bojowy"],
        cost: 50,
        number: 1,
        equipmentList:
          heroEquipment["Khazadzi z Gór Krańca Świata"].Bohaterowie,
        type: "Bohater",
        stats: {
          Początkowa: [3, 4, 4, 3, 4, 1, 2, 1, 9],
          Maksymalna: [4, 7, 6, 4, 5, 3, 5, 4, 10],
        },
        rules: [
          "Błogosławieństwo przodków",
          "Kowal Run",
          "Krzepki",
          "Nieustępliwość",
          "Odporność na magię (2)",
          "Pomiot podmroku",
          "Rankor",
          "Trudny do zabicia",
          "Uporczywość",
          "Wojownik podziemny",
          "Zabobonny lęk",
        ],
        exp: 12,
        skills: [0, 2, 3, 5],
      },
      "Mistrz Inżynier": {
        id: 2,
        startingEquipment: ["Sztylet", "Buława/Maczuga/Młot bojowy"],
        cost: 50,
        number: 1,
        equipmentList:
          heroEquipment["Khazadzi z Gór Krańca Świata"].Bohaterowie,
        type: "Bohater",
        stats: {
          Początkowa: [3, 4, 4, 3, 4, 1, 2, 1, 9],
          Maksymalna: [4, 7, 6, 4, 5, 3, 5, 4, 10],
        },
        rules: [
          "Drużyna obsługi",
          "Inżynier",
          "Krzepki",
          "Mistrz inżynier",
          "Nieustępliwość",
          "Odporność na magię (2)",
          "Pomiot podmroku",
          "Rankor",
          "Trudny do zabicia",
          "Uporczywość",
          "Wojownik podziemny",
          "Zabobonny lęk",
        ],
        exp: 12,
        skills: [0, 1, 2, 3, 5],
      },
      Długobrody: {
        id: 3,
        startingEquipment: ["Sztylet", "Broń wielka"],
        cost: 45,
        number: 1,
        equipmentList:
          heroEquipment["Khazadzi z Gór Krańca Świata"].Bohaterowie,
        type: "Bohater",
        stats: {
          Początkowa: [3, 5, 3, 3, 4, 1, 2, 1, 9],
          Maksymalna: [4, 7, 6, 4, 5, 3, 5, 4, 10],
        },
        rules: [
          "Krzepki",
          "Nieustępliwość",
          "Odporność na magię (2)",
          "Pomiot podmroku",
          "Rankor",
          "Trudny do zabicia",
          "Uporczywość",
          "Wojownik podziemny",
          "Zabobonny lęk",
          "Zimnokrwisty",
        ],
        exp: 10,
        skills: [0, 3, 5],
      },
      "Łamacz Żelaza": {
        id: 4,
        startingEquipment: ["Sztylet", "Topór krasnoludów"],
        cost: 40,
        number: 1,
        equipmentList:
          heroEquipment["Khazadzi z Gór Krańca Świata"].Bohaterowie,
        type: "Bohater",
        stats: {
          Początkowa: [3, 5, 3, 3, 4, 1, 2, 1, 9],
          Maksymalna: [4, 7, 6, 4, 5, 3, 5, 4, 10],
        },
        rules: [
          "Krzepki",
          "Nieustępliwość",
          "Odporność na magię (2)",
          "Pomiot podmroku",
          "Rankor",
          "Trudny do zabicia",
          "Uporczywość",
          "Wojownik podziemny",
          "Zabobonny lęk",
          "Żelazoskóry",
        ],
        exp: 8,
        skills: [0, 3, 5],
      },
      "Wojownik Klanowy": {
        id: 5,
        startingEquipment: ["Sztylet"],
        cost: 25,
        number: 12,
        equipmentList: heroEquipment["Khazadzi z Gór Krańca Świata"].Stronnicy,
        type: "Stronnik",
        stats: {
          Początkowa: [3, 4, 3, 3, 4, 1, 2, 1, 9],
          Maksymalna: [4, 7, 6, 4, 5, 3, 5, 4, 10],
        },
        rules: [
          "Chorążowie & sygnaliści",
          "Drużyna obsługi",
          "Krzepki",
          "Nieustępliwość",
          "Odporność na magię (2)",
          "Pomiot podmroku",
          "Rankor",
          "Trudny do zabicia",
          "Uporczywość",
          "Wojownik podziemny",
          "Zabobonny lęk",
        ],
      },
      Strzelec: {
        id: 6,
        startingEquipment: ["Sztylet"],
        cost: 45,
        number: 5,
        equipmentList: heroEquipment["Khazadzi z Gór Krańca Świata"].Strzelec,
        type: "Stronnik",
        stats: {
          Początkowa: [3, 4, 3, 3, 4, 1, 2, 1, 9],
          Maksymalna: [4, 7, 6, 4, 5, 3, 5, 4, 10],
        },
        rules: [
          "Błyskawiczne przeładowanie",
          "Krzepki",
          "Nieustępliwość",
          "Odporność na magię (2)",
          "Pomiot podmroku",
          "Rankor",
          "Trudny do zabicia",
          "Uporczywość",
          "Wojownik podziemny",
          "Zabobonny lęk",
        ],
      },
      Górnik: {
        id: 7,
        startingEquipment: ["Sztylet", "Broń wielka"],
        cost: 40,
        number: 5,
        equipmentList: heroEquipment["Khazadzi z Gór Krańca Świata"].Stronnicy,
        type: "Stronnik",
        stats: {
          Początkowa: [3, 4, 3, 3, 4, 1, 2, 1, 9],
          Maksymalna: [4, 7, 6, 4, 5, 3, 5, 4, 10],
        },
        rules: [
          "Krzepki",
          "Nieustępliwość",
          "Odporność na magię (2)",
          "Pomiot podmroku",
          "Rankor",
          "Saper",
          "Trudny do zabicia",
          "Uporczywość",
          "Wojownik podziemny",
          "Zabobonny lęk",
          "Zasadzka",
          "Zwiadowca",
        ],
      },
      "Pogromca Trolli": {
        id: 8,
        startingEquipment: [
          "Topór krasnoludów",
          "Topór krasnoludów",
          "Broń wielka",
        ],
        cost: 50,
        number: 3,
        equipmentList: heroEquipment["Khazadzi z Gór Krańca Świata"].Pogromca,
        type: "Stronnik",
        stats: {
          Początkowa: [3, 4, 3, 3, 4, 1, 2, 1, 10],
          Maksymalna: [4, 7, 6, 4, 5, 3, 5, 4, 10],
        },
        rules: [
          "Fanatyk",
          "Krzepki",
          "Nieustępliwość",
          "Ochronne tatuaże",
          "Odporność na magię (2)",
          "Pogromca",
          "Pomiot podmroku",
          "Rankor",
          "Topory pogromcy",
          "Trudny do zabicia",
          "Uporczywość",
          "Wojownik podziemny",
          "Zabobonny lęk",
        ],
      },
      Żyrokopter: {
        id: 9,
        startingEquipment: ["Kusza powtarzalna"],
        cost: 150,
        number: 1,
        equipmentList: [],
        type: "Machina",
        stats: {
          Początkowa: [1, "-", "-", 4, 5, 5, "-", "-", "-"],
          Maksymalna: [1, "-", "-", 4, 5, 5, "-", "-", "-"],
        },
        rules: [
          "Bombardowanie",
          "Duży cel",
          "Lot",
          "Machina wojenna",
          "Trafienie z uderzenia",
          "Uporczywość",
          "Zwiadowca",
        ],
      },
    },
    limit: 500,
    minModels: 3,
    maxModels: 12,
    name: "Khazadzi z Gór Krańca Świata",
    nature: "Neutralna",
    armyRules: ["Kontakty handlowe (3)", "Reduta", "Zhańbiony"],
    mercenaries: [
      "Goniec",
      "Miotacz ołowiu",
      "Ochroniarz",
      "Ogniomistrz",
      "Poszukiwacz złota",
      "Strażnik dróg",
      "Zwiadowca",
    ],
  }