import { heroEquipment } from "../HeroEquipment";

export const pestilens = {
  heroes: {
    "Diakon Zarazy": {
      id: 0,
      startingEquipment: ["Sztylet", "Kostur"],
      cost: 75,
      number: 1,
      equipmentList: heroEquipment["Kult Zarazy klanu Pestilens"].Bohaterowie,
      type: "Bohater",
      stats: {
        Początkowa: [5, 4, 4, 3, 4, 2, 5, 1, 7],
        Maksymalna: [6, 6, 6, 4, 4, 3, 7, 4, 7],
      },
      rules: [
        "Dowódca",
        "Mag (Tradycja Zarazy)",
        "Ranger",
        "Trudny do zabicia",
      ],
      exp: 20,
      skills: [0, 1, 2, 4, 5],
    },
    "Mnich Zarazy": {
      id: 1,
      startingEquipment: ["Sztylet", "Buława/Maczuga/Młot bojowy"],
      cost: 35,
      number: 1,
      equipmentList: heroEquipment["Kult Zarazy klanu Pestilens"].Bohaterowie,
      type: "Bohater",
      stats: {
        Początkowa: [5, 3, 3, 3, 4, 1, 5, 1, 6],
        Maksymalna: [6, 6, 6, 4, 4, 3, 7, 4, 7],
      },
      rules: ["Ranger", "Trudny do zabicia"],
      exp: 8,
      skills: [0, 2, 4, 5],
    },
    Kadzielnik: {
      id: 2,
      startingEquipment: ["Sztylet", "Cep bojowy"],
      cost: 40,
      number: 1,
      equipmentList: heroEquipment["Kult Zarazy klanu Pestilens"].Bohaterowie,
      type: "Bohater",
      stats: {
        Początkowa: [5, 3, 3, 3, 4, 1, 5, 1, 5],
        Maksymalna: [6, 6, 6, 4, 4, 3, 7, 4, 7],
      },
      rules: ["Ranger", "Trudny do zabicia"],
      exp: 8,
      skills: [0, 3, 4, 5],
    },
    "Łowca niewolników": {
      id: 3,
      startingEquipment: ["Sztylet", "Łapacz"],
      cost: 45,
      number: 1,
      equipmentList: heroEquipment["Kult Zarazy klanu Pestilens"].Bohaterowie,
      type: "Bohater",
      stats: {
        Początkowa: [5, 3, 3, 3, 4, 1, 5, 1, 5],
        Maksymalna: [6, 6, 6, 4, 4, 3, 7, 4, 7],
      },
      rules: ["Handlarz niewolników", "Ranger", "Trudny do zabicia"],
      exp: 8,
      skills: [0, 1, 4, 5],
    },
    Niewolnik: {
      id: 4,
      startingEquipment: ["Broń improwizowana"],
      cost: 10,
      number: 15,
      equipmentList: {},
      type: "Stronnik",
      stats: {
        Początkowa: [4, 2, 2, 3, 3, 1, 3, 1, 2],
        Maksymalna: [5, 6, 6, 4, 4, 3, 6, 4, 9],
      },
      rules: ["Mięso armatnie", "Niewolnik", "Rozmiar rzondzi"],
    },
    "Czciciel Zarazy": {
      id: 5,
      startingEquipment: ["Sztylet", "Buława/Maczuga/Młot bojowy"],
      cost: 25,
      number: 15,
      equipmentList: heroEquipment["Kult Zarazy klanu Pestilens"].Stronnicy,
      type: "Stronnik",
      stats: {
        Początkowa: [5, 3, 3, 3, 3, 1, 4, 1, 5],
        Maksymalna: [6, 6, 6, 4, 4, 3, 7, 4, 7],
      },
      rules: [
        "Chorążowie & sygnaliści",
        "Drużyna obsługi",
        "Furia",
        "Ranger",
        "Trudny do zabicia",
      ],
    },
    "Siewca Zarazy": {
      id: 6,
      startingEquipment: ["Cep bojowy"],
      cost: 40,
      number: 5,
      equipmentList: heroEquipment["Kult Zarazy klanu Pestilens"].Stronnicy,
      type: "Stronnik",
      stats: {
        Początkowa: [5, 3, 3, 4, 4, 1, 4, 1, 10],
        Maksymalna: [6, 6, 6, 4, 4, 3, 7, 4, 7],
      },
      rules: ["Fanatyk", "Furia", "Ranger", "Trudny do zabicia"],
    },
    "Szczur Zarazy": {
      id: 7,
      startingEquipment: ["Broń naturalna (zatruty atak)"],
      cost: 30,
      number: 5,
      equipmentList: {},
      type: "Stronnik",
      stats: {
        Początkowa: [6, 3, 0, 3, 3, 1, 3, 1, 3],
        Maksymalna: [6, 3, 0, 3, 3, 1, 3, 1, 3],
      },
      rules: [
        "Furia",
        "Murołaz",
        "Sfora",
        "Rozmiar rzondzi",
        "Trudny do zabicia",
        "Zwierzę",
      ],
    },
    Rydwan: {
      id: 8,
      startingEquipment: [],
      cost: 125,
      number: 1,
      equipmentList: {},
      type: "Machina",
      stats: {
        Rydwan: ["-", "-", "-", 5, 5, 8, "-", "-", "-"],
        Wilkoszczur: [9, 3, 0, 3, "-", "-", 4, 1, 3],
        "Wilkoszczur ": [9, 3, 0, 3, "-", "-", 4, 1, 3],
      },
      rules: ["Duży cel", "Machina wojenna", "Rydwan"],
    },
    Więźniarka: {
      id: 9,
      startingEquipment: [],
      cost: 175,
      number: 1,
      equipmentList: {},
      type: "Machina",
      stats: {
        Powóz: ["-", "-", "-", 4, 8, 8, "-", "-", "-"],
        Wilkoszczur: [9, 3, 0, 3, "-", "-", 4, 1, 3],
        "Wilkoszczur ": [9, 3, 0, 3, "-", "-", 4, 1, 3],
      },
      rules: ["Duży cel", "Machina wojenna", "Powóz", "Więźniarka"],
    },
  },
  limit: 500,
  minModels: 3,
  maxModels: 15,
  name: "Kult Zarazy klanu Pestilens",
  nature: "Chaotyczna",
  armyRules: ["Rozrzutność", "W nogi!"],
  mercenaries: ["Szczurogr", "Szpieg", "Złodziej"],
};
