export const heroEquipment = {
    "Łowcy Czarownic": {
      Bohaterowie: {
        "Broń wielka": [10, 0],
        "Buława/Maczuga/Młot bojowy": [5, 0],
        "Gwiazda zaranna": [5, 0],
        "Kadzielnica Ognia": [20, 0],
        Miecz: [10, 0],
        Sztylet: [2, 0],
        "Topór bojowy/Nadziak": [5, 0],
        "Broń miotana(noże)": [10, 1],
        Kusza: [25, 1],
        Pistolet: [10, 1],
        "Pistolet pojedynkowy": [20, 1],
        "Pistolet strzałkowy": [20, 1],
        Lekki: [5, 2, "Zbroja"],
        Średni: [15, 2, "Zbroja"],
        Ciężki: [30, 2, "Zbroja"],
        Puklerz: [3, 2, "Tarcza"],
        Tarcza: [5, 2, "Tarcza"],
        Hełm: [5, 2],
      },
      Stronnicy: {
        "Broń wielka": [10, 0],
        "Buława/Maczuga/Młot bojowy": [5, 0],
        "Cep bojowy": [10, 0],
        "Gwiazda zaranna": [5, 0],
        Korbacz: [5, 0],
        Sztylet: [2, 0],
        "Broń miotana(noże)": [10, 1],
        Łuk: [10, 1],
        "Łuk długi": [20, 1],
        Oszczep: [15, 1],
        Proca: [5, 1],
        Sieć: [10, 1],
        Lekki: [5, 2, "Zbroja"],
        Średni: [15, 2, "Zbroja"],
        Puklerz: [3, 2, "Tarcza"],
        Tarcza: [5, 2, "Tarcza"],
        Hełm: [5, 2],
      },
      Flagelant: {
        "Broń wielka": [10, 0],
        Bicz: [15, 0],
        "Buława/Maczuga/Młot bojowy": [5, 0],
        "Cep bojowy": [10, 0],
        "Gwiazda zaranna": [5, 0],
        "Kadzielnica Ognia": [20, 0],
        Korbacz: [5, 0],
      },
      Rycerz: {
        "Broń wielka": [10, 0],
        "Buława/Maczuga/Młot bojowy": [5, 0],
        Kopia: [30, 0],
        Miecz: [10, 0],
        Sztylet: [2, 0],
        Włócznia: [10, 0],
        "Broń miotana(noże)": [10, 1],
        Lekki: [5, 2, "Zbroja"],
        Średni: [15, 2, "Zbroja"],
        Puklerz: [3, 2, "Tarcza"],
        Tarcza: [5, 2, "Tarcza"],
        Hełm: [5, 2],
      },
      Prezbiter: {
        "Broń wielka": [10, 0],
        "Buława/Maczuga/Młot bojowy": [5, 0],
        "Młot ulrykański": [15, 0],
        Sztylet: [2, 0],
        "Broń miotana(noże)": [10, 1],
        Pistolet: [10, 1],
        "Pistolet pojedynkowy": [20, 1],
        Lekki: [5, 2, "Zbroja"],
        Średni: [15, 2, "Zbroja"],
        Ciężki: [30, 2, "Zbroja"],
        Puklerz: [3, 2, "Tarcza"],
        Tarcza: [5, 2, "Tarcza"],
      },
    },
    "Cyrkowcy z Ligii Ostermarku": {
      Bohaterowie: {
        "Broń wielka": [10, 0],
        Bicz: [15, 0],
        "Buława/Maczuga/Młot bojowy": [5, 0],
        Kostur: [5, 0],
        Łapacz: [10, 0],
        Miecz: [10, 0],
        Sztylet: [2, 0],
        "Topór bojowy/Nadziak": [5, 0],
        Włócznia: [10, 0],
        "Broń miotana(noże)": [10, 1],
        Kusza: [25, 1],
        Pistolet: [10, 1],
        "Pistolet pojedynkowy": [20, 1],
        Lekki: [5, 2, "Zbroja"],
        Średni: [15, 2, "Zbroja"],
        Ciężki: [30, 2, "Zbroja"],
        Puklerz: [3, 2, "Tarcza"],
        Tarcza: [5, 2, "Tarcza"],
        Hełm: [5, 2],
      },
      "Magister magii": {
        Kostur: [5, 0],
        Miecz: [10, 0],
        Sztylet: [2, 0],
        "Broń miotana(noże)": [10, 1],
      },
      "Kapłan Ranalda": {
        Kostur: [5, 0],
        Miecz: [10, 0],
        Sztylet: [2, 0],
        "Broń miotana(noże)": [10, 1],
        Bolas: [10, 1],
      },
      Stronnicy: {
        "Broń wielka": [10, 0],
        "Buława/Maczuga/Młot bojowy": [5, 0],
        Halabarda: [10, 0],
        Miecz: [10, 0],
        Sztylet: [2, 0],
        "Topór bojowy/Nadziak": [5, 0],
        Włócznia: [10, 0],
        "Broń miotana(noże)": [10, 1],
        Łuk: [10, 1],
        "Łuk krótki": [5, 1],
        Lekki: [5, 2, "Zbroja"],
        Średni: [15, 2, "Zbroja"],
        Puklerz: [3, 2, "Tarcza"],
        Tarcza: [5, 2, "Tarcza"],
        Hełm: [5, 2],
      },
      Ogr: {
        "Broń wielka": [10, 0],
        "Buława/Maczuga/Młot bojowy": [5, 0],
        "Cep bojowcy": [10, 0],
        "Karwasz bojowy": [15, 0],
        Miecz: [10, 0],
        "Maczuga ogrów": [5, 0],
        "Topór bojowy/Nadziak": [5, 0],
        "Broń miotana(noże)": [10, 1],
        Ołowiomiotacz: [50, 1],
        Lekki: [10, 2, "Zbroja"],
        Średni: [30, 2, "Zbroja"],
      },
    },
    "Muszkieterzy z Nuln": {
      Bohaterowie: {
        "Broń wielka": [10, 0],
        Bagnet: [5, 0],
        "Buława/Maczuga/Młot bojowy": [5, 0],
        Halabarda: [10, 0],
        Miecz: [10, 0],
        Sztylet: [2, 0],
        "Broń miotana(ładunki wybuchowe)": [15, 1],
        "Gołąb bombardujący": [25, 1],
        Granatnik: [35, 1],
        "Muszkiet dubeltowy": [40, 1],
        "Muszkiet krasnoludzki": [25, 1],
        Pistolet: [10, 1],
        "Pistolet dubeltowy": [15, 1],
        "Pistolet pojedynkowy": [20, 1],
        Revolvera: [50, 1],
        Lekki: [5, 2, "Zbroja"],
        Średni: [15, 2, "Zbroja"],
        Ciężki: [30, 2, "Zbroja"],
        Puklerz: [3, 2, "Tarcza"],
        Tarcza: [5, 2, "Tarcza"],
        Hełm: [5, 2],
      },
      Prezbiter: {
        "Broń wielka": [10, 0],
        "Buława/Maczuga/Młot bojowy": [5, 0],
        "Młot ulrykański": [15, 0],
        Sztylet: [2, 0],
        "Broń miotana(noże)": [10, 1],
        Pistolet: [10, 1],
        "Pistolet pojedynkowy": [20, 1],
        Lekki: [5, 2, "Zbroja"],
        Średni: [15, 2, "Zbroja"],
        Ciężki: [30, 2, "Zbroja"],
        Puklerz: [3, 2, "Tarcza"],
        Tarcza: [5, 2, "Tarcza"],
      },
      Stronnicy: {
        "Broń wielka": [10, 0],
        Bagnet: [5, 0],
        "Buława/Maczuga/Młot bojowy": [5, 0],
        Halabarda: [10, 0],
        Miecz: [10, 0],
        Sztylet: [2, 0],
        "Broń miotana(ładunki wybuchowe)": [15, 1],
        Arkebuz: [30, 1],
        Falkonet: [40, 1],
        Garłacz: [30, 1],
        Muszkiet: [25, 1],
        "Muszkiet dubeltowy": [40, 1],
        "Muszkiet hochlandzki": [50, 1],
        Revolvera: [50, 1],
        Lekki: [5, 2, "Zbroja"],
        Średni: [15, 2, "Zbroja"],
        Puklerz: [3, 2, "Tarcza"],
        Tarcza: [5, 2, "Tarcza"],
        Hełm: [5, 2],
      },
      Rajtar: {
        Miecz: [10, 0],
        Sztylet: [2, 0],
        Włócznia: [10, 0],
        Pistolet: [10, 1],
        "Pistolet pojedynkowy": [20, 1],
        Lekki: [5, 2, "Zbroja"],
        Średni: [15, 2, "Zbroja"],
        Hełm: [5, 2],
      },
      Ranger: {
        "Broń wielka": [10, 0],
        "Buława/Maczuga/Młot bojowy": [5, 0],
        "Cep bojowy": [5, 0],
        Sztylet: [2, 0],
        "Topór bojowy/Nadziak": [5, 0],
        "Topór krasnoludów": [10, 0],
        "Broń miotana(ładunki wybuchowe)": [15, 1],
        Kusza: [25, 1],
        Oszczep: [15, 1],
        Lekki: [5, 2, "Zbroja"],
        Średni: [15, 2, "Zbroja"],
        Tarcza: [5, 2, "Tarcza"],
        Hełm: [5, 2],
      },
    },
    "Piechota Morska z Marienburga": {
      Bohaterowie: {
        "Broń wielka": [10, 0],
        "Buława/Maczuga/Młot bojowy": [5, 0],
        Korbacz: [5, 0],
        Kostur: [5, 0],
        "Łamacz mieczy": [25, 0],
        Miecz: [10, 0],
        Rapier: [10, 0],
        Sztylet: [2, 0],
        "Topór bojowy/Nadziak": [5, 0],
        Trójząb: [15, 0],
        Włócznia: [10, 0],
        "Broń miotana(noże)": [10, 1],
        Łuk: [10, 1],
        "Łuk długi": [20, 1],
        Kusza: [25, 1],
        Pistolet: [10, 1],
        "Pistolet pojedynkowy": [20, 1],
        Lekki: [5, 2, "Zbroja"],
        Średni: [15, 2, "Zbroja"],
        Ciężki: [30, 2, "Zbroja"],
        Puklerz: [3, 2, "Tarcza"],
        Tarcza: [5, 2, "Tarcza"],
        Hełm: [5, 2],
      },
      Stronnicy: {
        "Broń wielka": [10, 0],
        Bosak: [15, 0],
        "Buława/Maczuga/Młot bojowy": [5, 0],
        Halabarda: [10, 0],
        Korbacz: [5, 0],
        Miecz: [10, 0],
        Sztylet: [2, 0],
        "Topór bojowy/Nadziak": [5, 0],
        Trójząb: [15, 0],
        Włócznia: [10, 0],
        "Broń miotana(noże)": [10, 1],
        Garłacz: [30, 1],
        Łuk: [10, 1],
        "Łuk długi": [20, 1],
        Kusza: [25, 1],
        Muszkiet: [25, 1],
        Oszczep: [15, 1],
        Lekki: [5, 2, "Zbroja"],
        Średni: [15, 2, "Zbroja"],
        Puklerz: [3, 2, "Tarcza"],
        Tarcza: [5, 2, "Tarcza"],
        Hełm: [5, 2],
      },
      Bukanier: {
        "Buława/Maczuga/Młot bojowy": [5, 0],
        "Cep bojowy": [10, 0],
        Miecz: [10, 0],
        Sztylet: [2, 0],
        "Topór bojowy/Nadziak": [5, 0],
        "Topór krasnoludów": [10, 0],
        "Broń miotana(ładunki wybuchowe)": [15, 1],
        Garłacz: [30, 1],
        Pistolet: [10, 1],
        "Pistolet pojedynkowy": [20, 1],
      },
      Kapłan: {
        "Broń wielka": [10, 0],
        Miecz: [10, 0],
        Sztylet: [2, 0],
        Trójząb: [15, 0],
        Włócznia: [10, 0],
        "Broń miotana(noże)": [10, 1],
        Oszczep: [15, 1],
        Lekki: [5, 2, "Zbroja"],
        Średni: [15, 2, "Zbroja"],
        Puklerz: [3, 2, "Tarcza"],
        Tarcza: [5, 2, "Tarcza"],
        Hełm: [5, 2],
      },
    },
    "Leśni Elfowie z Athel Loren": {
      Bohaterowie: {
        "Broń wielka": [10,0],
        "Kostur": [5,0],
        Miecz: [10,0],
        Saearath: [15,0],
        Sztylet: [2, 0],
        "Topór bojowy/Nadziak": [5, 0],
        Włócznia: [10,0],
        "Broń miotana(topory/młoty)": [15,1],
        Łuk: [10,1],
        "Łuk elfów": [35,1],
        "Łuk długi": [20,1],
        Oszczep: [15,1],
        Lekki: [5, 2, "Zbroja"],
        Średni: [15, 2, "Zbroja"],
        "Pancerz z Ithilmaru": [50, 2, "Zbroja"],
        Tarcza: [5, 2, "Tarcza"],
        Hełm: [5, 2],
      },
      Mag: {
        "Kostur": [5,0],
        Miecz: [10,0],
        Sztylet: [2, 0],
        Włócznia: [10,0],
        "Broń miotana(topory/młoty)": [15,1],
        "Łuk elfów": [35,1],
        Oszczep: [15,1],
      },
      Stronnicy: {
        "Broń wielka": [10,0],
        Miecz: [10,0],
        Sztylet: [2, 0],
        "Topór bojowy/Nadziak": [5, 0],
        Włócznia: [10,0],
        "Broń miotana(topory/młoty)": [15,1],
        Łuk: [10,1],
        "Łuk długi": [20,1],
        Oszczep: [15,1],
        Proca: [5,1],
        Lekki: [5, 2, "Zbroja"],
        Średni: [15, 2, "Zbroja"],
        Puklerz: [3, 2, "Tarcza"],
        Tarcza: [5, 2, "Tarcza"],
        Hełm: [5, 2],
      },
      Tancerz: {
        "Broń wielka": [10,0],
        Miecz: [10,0],
        Sztylet: [2, 0],
        Włócznia: [10,0],
        "Broń miotana(topory/młoty)": [15,1],
      }
    },
    "Khazadzi z Gór Krańca Świata": {
      Bohaterowie: {
        "Broń wielka": [10, 0],
        "Buława/Maczuga/Młot bojowy": [5, 0],
        "Cep bojowy": [10, 0],
        Sztylet: [2, 0],
        "Topór bojowy/Nadziak": [5, 0],
        "Topór krasnoludów": [10,0],
        "Broń miotana(ładunki wybuchowe)": [15, 1],
        Kusza: [25, 1],
        "Muszkiet krasnoludzki": [25, 1],
        "Pistolet dubeltowy": [15,1],
        "Pistolet pojedynkowy": [20, 1],
        Lekki: [5, 2, "Zbroja"],
        Średni: [15, 2, "Zbroja"],
        Ciężki: [30, 2, "Zbroja"],
        "Pancerz z Gromrilu": [50, 2, "Zbroja"],
        Tarcza: [5, 2, "Tarcza"],
        Hełm: [5, 2],
      },
      Stronnicy: {
        "Broń wielka": [10, 0],
        "Buława/Maczuga/Młot bojowy": [5, 0],
        "Cep bojowy": [10, 0],
        Sztylet: [2, 0],
        "Topór bojowy/Nadziak": [5, 0],
        "Topór krasnoludów": [10,0],
        "Broń miotana(ładunki wybuchowe)": [15, 1],
        "Garłacz": [30,1],
        Kusza: [25, 1],
        "Muszkiet krasnoludzki": [25, 1],
        "Oszczep": [15, 1],
        Lekki: [5, 2, "Zbroja"],
        Średni: [15, 2, "Zbroja"],
        Tarcza: [5, 2, "Tarcza"],
        Hełm: [5, 2],
      },
      Strzelec: {
        "Broń wielka": [10, 0],
        "Buława/Maczuga/Młot bojowy": [5, 0],
        "Cep bojowy": [10, 0],
        Sztylet: [2, 0],
        "Topór bojowy/Nadziak": [5, 0],
        "Topór krasnoludów": [10,0],
        "Broń miotana(ładunki wybuchowe)": [15, 1],
        "Garłacz": [30,1],
        Kusza: [25, 1,"Startowy"],
        "Muszkiet krasnoludzki": [25, 1,"Startowy"],
        "Oszczep": [15, 1],
        Lekki: [5, 2, "Zbroja"],
        Średni: [15, 2, "Zbroja"],
        Tarcza: [5, 2, "Tarcza"],
        Hełm: [5, 2],
      },
      Pogromca: {
        "Broń wielka": [10, 0],
        "Buława/Maczuga/Młot bojowy": [5, 0],
        "Cep bojowy": [10, 0],
        "Topór bojowy/Nadziak": [5, 0],
        "Topór krasnoludów": [10,0],
      }
    }
  };